/**
 * MOCK SPACETIMEDB BINDINGS
 * This file would normally be auto-generated by `spacetime generate`.
 * For the simulation, we define the types and hooks manually here.
 */

export interface User {
    identity: string;
    username: string;
    display_name: string | null;
    level: number;
    xp: number;
    streak: number;
    longest_streak: number;
    last_activity: number; // Timestamp
    avatar_url: string | null;
    is_online: boolean;
    created_at: number;
}

export interface UserProgress {
    identity: string;
    completed_labs: string[];
    completed_modules: number[];
    unlocked_modules: number[];
    achievements: string[];
    activity_log: string; // JSON encoded
}

export interface LabState {
    id: number;
    user_identity: string;
    lab_id: string;
    vfs_snapshot: string;
    started_at: number;
    completed_at: number | null;
    current_step: number;
    verified: boolean;
}

export interface OnlinePresence {
    identity: string;
    last_seen: number;
    current_lab: string | null;
}

export interface Message {
    id: string;
    sender: string;
    content: string;
    channel: string; // "global", "lab:id", "dm:id1:id2"
    timestamp: number;
    edited: number | null;
    deleted: boolean;
    pinned: boolean;
}

export interface TypingIndicator {
    identity: string;
    channel: string;
    started_at: number;
}

// Mock database type
export interface Db {
    user: {
        filter_by_identity: (identity: string) => User | undefined;
    };
    user_progress: {
        filter_by_identity: (identity: string) => UserProgress | undefined;
    };
    online_presence: {
        all: () => OnlinePresence[];
    };
    message: {
        filter_by_channel: (channel: string) => Message[];
        all: () => Message[];
    };
    typing_indicator: {
        filter_by_channel: (channel: string) => TypingIndicator[];
    };
}
