// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  userIdentity: __t.identity().name("user_identity"),
  labId: __t.string().name("lab_id"),
  vfsSnapshot: __t.string().name("vfs_snapshot"),
  startedAt: __t.timestamp().name("started_at"),
  completedAt: __t.option(__t.timestamp()).name("completed_at"),
  currentStep: __t.u32().name("current_step"),
  verified: __t.bool(),
});
