// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const LabState = __t.object("LabState", {
  id: __t.u64(),
  userIdentity: __t.identity(),
  labId: __t.string(),
  vfsSnapshot: __t.string(),
  startedAt: __t.timestamp(),
  completedAt: __t.option(__t.timestamp()),
  currentStep: __t.u32(),
  verified: __t.bool(),
});
export type LabState = __Infer<typeof LabState>;

export const LeaderboardEntry = __t.object("LeaderboardEntry", {
  identity: __t.identity(),
  rank: __t.u64(),
  totalXp: __t.u64(),
  level: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type LeaderboardEntry = __Infer<typeof LeaderboardEntry>;

export const Message = __t.object("Message", {
  id: __t.u64(),
  senderIdentity: __t.identity(),
  content: __t.string(),
  channel: __t.string(),
  timestamp: __t.timestamp(),
  edited: __t.option(__t.timestamp()),
  deleted: __t.bool(),
  pinned: __t.bool(),
});
export type Message = __Infer<typeof Message>;

export const OnlinePresence = __t.object("OnlinePresence", {
  identity: __t.identity(),
  lastSeen: __t.timestamp(),
  currentLab: __t.option(__t.string()),
});
export type OnlinePresence = __Infer<typeof OnlinePresence>;

export const TypingIndicator = __t.object("TypingIndicator", {
  identity: __t.identity(),
  channel: __t.string(),
  startedAt: __t.timestamp(),
});
export type TypingIndicator = __Infer<typeof TypingIndicator>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.string(),
  displayName: __t.option(__t.string()),
  level: __t.u32(),
  xp: __t.u64(),
  streak: __t.u32(),
  longestStreak: __t.u32(),
  lastActivity: __t.timestamp(),
  avatarUrl: __t.option(__t.string()),
  isOnline: __t.bool(),
  createdAt: __t.timestamp(),
});
export type User = __Infer<typeof User>;

export const UserProgress = __t.object("UserProgress", {
  identity: __t.identity(),
  completedLabs: __t.array(__t.string()),
  completedModules: __t.array(__t.u32()),
  unlockedModules: __t.array(__t.u32()),
  achievements: __t.array(__t.string()),
});
export type UserProgress = __Infer<typeof UserProgress>;

