// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  displayName: __t.option(__t.string()).name("display_name"),
  level: __t.u32(),
  xp: __t.u64(),
  streak: __t.u32(),
  longestStreak: __t.u32().name("longest_streak"),
  lastActivity: __t.timestamp().name("last_activity"),
  avatarUrl: __t.option(__t.string()).name("avatar_url"),
  isOnline: __t.bool().name("is_online"),
  isAdmin: __t.bool().name("is_admin"),
  createdAt: __t.timestamp().name("created_at"),
});
