// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.2 (commit bc4fcec6f33f607fb46f61ae66c479eecf5a6e74).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CleanupOfflineUsersReducer from "./cleanup_offline_users_reducer";
import CompleteLabReducer from "./complete_lab_reducer";
import HeartbeatReducer from "./heartbeat_reducer";
import RegisterUserReducer from "./register_user_reducer";
import SendMessageReducer from "./send_message_reducer";
import EditMessageReducer from "./edit_message_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import StartTypingReducer from "./start_typing_reducer";
import StopTypingReducer from "./stop_typing_reducer";
import CreateChannelReducer from "./create_channel_reducer";
import UpdateStreakReducer from "./update_streak_reducer";
import PinMessageReducer from "./pin_message_reducer";
import CompleteQuestReducer from "./complete_quest_reducer";
import UpvoteMessageReducer from "./upvote_message_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import LabStateRow from "./lab_state_table";
import LeaderboardEntryRow from "./leaderboard_entry_table";
import MessageRow from "./message_table";
import OnlinePresenceRow from "./online_presence_table";
import TypingIndicatorRow from "./typing_indicator_table";
import UserRow from "./user_table";
import UserProgressRow from "./user_progress_table";
import ChannelRow from "./channel_table";
import QuestRow from "./quest_table";
import UserQuestRow from "./user_quest_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  lab_state: __table({
    name: 'lab_state',
    indexes: [
      {
        name: 'id', algorithm: 'btree', columns: [
          'id',
        ]
      },
    ],
    constraints: [
      { name: 'lab_state_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, LabStateRow),
  leaderboard_entry: __table({
    name: 'leaderboard_entry',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
    ],
    constraints: [
      { name: 'leaderboard_entry_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, LeaderboardEntryRow),
  message: __table({
    name: 'message',
    indexes: [
      {
        name: 'id', algorithm: 'btree', columns: [
          'id',
        ]
      },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  online_presence: __table({
    name: 'online_presence',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
    ],
    constraints: [
      { name: 'online_presence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, OnlinePresenceRow),
  typing_indicator: __table({
    name: 'typing_indicator',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
    ],
    constraints: [
      { name: 'typing_indicator_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, TypingIndicatorRow),
  user: __table({
    name: 'user',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
      {
        name: 'username', algorithm: 'btree', columns: [
          'username',
        ]
      },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
      { name: 'user_username_key', constraint: 'unique', columns: ['username'] },
    ],
  }, UserRow),
  user_progress: __table({
    name: 'user_progress',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
    ],
    constraints: [
      { name: 'user_progress_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserProgressRow),
  channel: __table({
    name: 'channel',
    indexes: [
      {
        name: 'name', algorithm: 'btree', columns: [
          'name',
        ]
      },
    ],
    constraints: [
      { name: 'channel_name_key', constraint: 'unique', columns: ['name'] },
    ],
  }, ChannelRow),
  quest: __table({
    name: 'quest',
    indexes: [
      {
        name: 'id', algorithm: 'btree', columns: [
          'id',
        ]
      },
    ],
    constraints: [
      { name: 'quest_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, QuestRow),
  user_quest: __table({
    name: 'user_quest',
    indexes: [
      {
        name: 'identity', algorithm: 'btree', columns: [
          'identity',
        ]
      },
    ],
    constraints: [
      { name: 'user_quest_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserQuestRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("cleanup_offline_users", CleanupOfflineUsersReducer),
  __reducerSchema("complete_lab", CompleteLabReducer),
  __reducerSchema("heartbeat", HeartbeatReducer),
  __reducerSchema("register_user", RegisterUserReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("edit_message", EditMessageReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("start_typing", StartTypingReducer),
  __reducerSchema("stop_typing", StopTypingReducer),
  __reducerSchema("create_channel", CreateChannelReducer),
  __reducerSchema("update_streak", UpdateStreakReducer),
  __reducerSchema("pin_message", PinMessageReducer),
  __reducerSchema("complete_quest", CompleteQuestReducer),
  __reducerSchema("upvote_message", UpvoteMessageReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.2" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);


/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Table Row Types */
export type LabState = __Infer<typeof LabStateRow>;
export type LeaderboardEntry = __Infer<typeof LeaderboardEntryRow>;
export type Message = __Infer<typeof MessageRow>;
export type OnlinePresence = __Infer<typeof OnlinePresenceRow>;
export type TypingIndicator = __Infer<typeof TypingIndicatorRow>;
export type User = __Infer<typeof UserRow>;
export type UserProgress = __Infer<typeof UserProgressRow>;
export type Channel = __Infer<typeof ChannelRow>;
export type Quest = __Infer<typeof QuestRow>;
export type UserQuest = __Infer<typeof UserQuestRow>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> { }

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> { }

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

