// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  completedLabs: __t.array(__t.string()).name("completed_labs"),
  completedModules: __t.array(__t.u32()).name("completed_modules"),
  unlockedModules: __t.array(__t.u32()).name("unlocked_modules"),
  achievements: __t.array(__t.string()),
  activityLog: __t.array(__t.object("ActivityEntry", {
    timestamp: __t.timestamp(),
    action: __t.string(),
    metadata: __t.string(),
  })).name("activity_log"),
});
