import { CommandRegistry } from '../registry';
import { ls } from './ls';
import { pwd } from './pwd';
import { cd } from './cd';
import { mkdir } from './mkdir';
import { touch } from './touch';
import { cat } from './cat';
import { rm } from './rm';
import { cp } from './cp';
import { mv } from './mv';
import { grep } from './grep';
import { chmod } from './chmod';
import { chown } from './chown';
import { ln } from './ln';
import { sudo } from './sudo';
import { whoami } from './whoami';
import { date } from './date';
import { clear } from './clear';
import { help } from './help';
import { echo } from './echo';
import { history } from './history';
import { true_cmd, false_cmd } from './boolean';
import { uname, uptime, df, free } from './system';
import { ps, top, kill } from './process';
import { head, tail } from './head_tail';
import { wc } from './wc';
import { find } from './find';
import { sleep } from './sleep';
import { env } from './env';
import { id, groups } from './identity';
import { su } from './su';
import { printf } from './printf';
import { du } from './du';
import { which } from './which';
import { hostname } from './hostname';
import { rmdir, dirname, basename } from './path';
import { jobs, fg, bg } from './process';
import { alias, unalias } from './alias';
import { sort, uniq, cut } from './text';
import { tee, xargs } from './io';
import { sed, awk } from './sed_awk';
import { tar, gzip, gunzip } from './archive';
import { useradd, passwd } from './admin';
import { dig } from './network';
import { curl } from './curl';
import { yum, dnf } from './pkg';
import { man } from './man';
import { apt, aptGet } from './apt';
import { script } from './script';
import { strace } from './strace';
import { lsof } from './lsof';
import { who } from './who';
import { stat } from './stat';

// Register Core Commands
CommandRegistry.register('ls', ls);
CommandRegistry.register('pwd', pwd);
CommandRegistry.register('cd', cd);
CommandRegistry.register('mkdir', mkdir);
CommandRegistry.register('touch', touch);
CommandRegistry.register('cat', cat);
CommandRegistry.register('rm', rm);
CommandRegistry.register('cp', cp);
CommandRegistry.register('mv', mv);
CommandRegistry.register('grep', grep);
CommandRegistry.register('chmod', chmod);
CommandRegistry.register('chown', chown);
CommandRegistry.register('ln', ln);
CommandRegistry.register('sudo', sudo);
CommandRegistry.register('whoami', whoami);
CommandRegistry.register('date', date);
CommandRegistry.register('clear', clear);
CommandRegistry.register('help', help);
CommandRegistry.register('echo', echo);
CommandRegistry.register('history', history);
CommandRegistry.register('true', true_cmd);
CommandRegistry.register('false', false_cmd);
CommandRegistry.register('uname', uname);
CommandRegistry.register('uptime', uptime);
CommandRegistry.register('df', df);
CommandRegistry.register('free', free);
CommandRegistry.register('ps', ps);
CommandRegistry.register('top', top);
CommandRegistry.register('kill', kill);
CommandRegistry.register('head', head);
CommandRegistry.register('tail', tail);
CommandRegistry.register('wc', wc);
CommandRegistry.register('find', find);
CommandRegistry.register('sleep', sleep);
CommandRegistry.register('env', env);
CommandRegistry.register('id', id);
CommandRegistry.register('groups', groups);
CommandRegistry.register('su', su);
CommandRegistry.register('printf', printf);
CommandRegistry.register('du', du);
CommandRegistry.register('which', which);
CommandRegistry.register('hostname', hostname);
CommandRegistry.register('rmdir', rmdir);
CommandRegistry.register('dirname', dirname);
CommandRegistry.register('basename', basename);
CommandRegistry.register('jobs', jobs);
CommandRegistry.register('fg', fg);
CommandRegistry.register('bg', bg);
CommandRegistry.register('alias', alias);
CommandRegistry.register('unalias', unalias);
CommandRegistry.register('sort', sort);
CommandRegistry.register('uniq', uniq);
CommandRegistry.register('cut', cut);
CommandRegistry.register('tee', tee);
CommandRegistry.register('xargs', xargs);
CommandRegistry.register('sed', sed);
CommandRegistry.register('awk', awk);
CommandRegistry.register('tar', tar);
CommandRegistry.register('gzip', gzip);
CommandRegistry.register('gunzip', gunzip);
CommandRegistry.register('useradd', useradd);
CommandRegistry.register('passwd', passwd);
CommandRegistry.register('dig', dig);
CommandRegistry.register('curl', curl);
CommandRegistry.register('yum', yum);
CommandRegistry.register('dnf', dnf);
CommandRegistry.register('man', man);
CommandRegistry.register('apt', apt);
CommandRegistry.register('apt-get', aptGet);
CommandRegistry.register('script', script);
CommandRegistry.register('strace', strace);
CommandRegistry.register('lsof', lsof);
CommandRegistry.register('who', who);
CommandRegistry.register('stat', stat);

// Finished modularization of legacy modules
