// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CleanupOfflineUsersReducer from "../cleanup_offline_users_reducer";
import CompleteLabReducer from "../complete_lab_reducer";
import HeartbeatReducer from "../heartbeat_reducer";
import RegisterUserReducer from "../register_user_reducer";
import SendMessageReducer from "../send_message_reducer";

export type CleanupOfflineUsersParams = __Infer<typeof CleanupOfflineUsersReducer>;
export type CompleteLabParams = __Infer<typeof CompleteLabReducer>;
export type HeartbeatParams = __Infer<typeof HeartbeatReducer>;
export type RegisterUserParams = __Infer<typeof RegisterUserReducer>;
export type SendMessageParams = __Infer<typeof SendMessageReducer>;

