export interface ChapterSection {
    title: string;
    content: string;
}

export interface ChapterContent {
    chapterId: string;
    sections: ChapterSection[];
}

export const chapterContents: Record<string, ChapterContent> = {
    'sys1-ch01': {
        chapterId: 'sys1-ch01',
        sections: [
            {
                title: 'Introduction to Linux Mastery',
                content: `Linux is not just an operating system; it is the backbone of the modern internet, cloud computing, and high-performance clusters. Mastering Linux means gaining direct control over your system, understanding the principles of open-source collaboration, and developing the skills required to manage everything from a personal server to a massive corporate infrastructure.

In this track, we move beyond the superficial "click-and-point" interfaces of consumer operating systems and dive into the "Terminal-First" philosophy. This approach prioritizes efficiency, automation, and deep system understanding. By the end of this curriculum, you will not just be a "user" of Linux, but a skilled practitioner capable of architecting and maintaining complex systems.

**Key Mastery Principles:**
*   **The Command Line is Truth:** GUI tools are abstractions. The CLI provides the raw, unadulterated power of the system.
*   **Everything is a File:** From hardware devices to system configurations, Linux treats almost everything as a file, making the filesystem the ultimate configuration interface.
*   **Small Tools, Big Results:** The Unix philosophy of building small, focused tools that do one thing well and piping them together is the secret to Linux productivity.

*Example Showcase:* Instead of searching through menus to find a specific setting, a single command like \`grep -r "SearchTerm" /etc/\` can find configuration entries across thousands of files in milliseconds.`
            },
            {
                title: 'The Graphical Interface vs. The TTY',
                content: `While modern Linux distributions often come with beautiful desktop environments like GNOME, KDE, or XFCE, a professional administrator must be equally comfortable in a headless environment. The Graphical User Interface (GUI) is excellent for multitasking and media, but the TeleTYpe (TTY) or terminal is where the heavy lifting happens.

GNOME (GNU Network Object Model Environment) is the default for many professional-grade distributions. It provides a distraction-free workflow with the "Activities Overview" serving as a central hub for window management. However, as your skills grow, you'll find yourself spending more time in terminal emulators like GNOME Terminal, Alacritty, or Kitty.

**Understanding the Stack:**
1.  **The Kernel:** The heart of the system that manages hardware and memory.
2.  **The Shell:** The command interpreter (like Bash or Zsh) that translates your keystrokes into system calls.
3.  **The Terminal Emulator:** The windowed application that gives you a visual interface to the shell.

*Use Case:* Imagine you need to update 50 servers. Doing this through a GUI would take hours. Using a shell and a small script, you can trigger the update on all 50 machines simultaneously with a single command.`
            },
            {
                title: 'The Architecture of the Shell',
                content: `When you open a terminal, you are greeted by a "prompt." This prompt is generated by your shell, most commonly Bash (Bourne Again SHell). The shell is your primary interface for interacting with the Linux kernel. It supports variables, loops, conditional logic, and most importantly, command execution.

The shell follows a specific execution cycle:
1.  **Read:** It waits for you to type a command and hit Enter.
2.  **Evaluate:** It parses the command, expands variables, and finds the executable in your system's PATH.
3.  **Execute:** It tells the kernel to start a new process for that command.
4.  **Loop:** It returns the prompt and waits for the next instruction.

*Example:* When you type \`ls -l\`, the shell finds the \`ls\` binary in \`/usr/bin\`, tells the kernel to run it with the \`-l\` argument, captures the output, and prints it to your screen. Understanding this lifecycle is critical for troubleshooting "command not found" errors or permission issues.`
            }
        ]
    },
    'sys1-ch02': {
        chapterId: 'sys1-ch02',
        sections: [
            {
                title: 'Navigating the Unified Filesystem',
                content: `Unlike Windows, which uses drive letters like C: and D:, Linux uses a single unified tree structure. Everything starts at the **Root** directory, represented by a single forward slash (\`/\`). Every file, directory, and even hardware device is a branch on this tree.

Navigating this tree efficiently is a foundational skill. The \`cd\` (change directory) command is your primary tool for movement, and \`pwd\` (print working directory) tells you exactly where you are in the vast forest of the filesystem.

**The Power of Paths:**
*   **Absolute Paths:** Always start from the root (\`/\`). They are unambiguous and work from anywhere. Example: \`/var/log/syslog\`.
*   **Relative Paths:** Start from your current location. They are shorter but depend on context. Example: \`../backups/old_logs\`.
*   **The Dot Notation:** Use \`.\` to refer to "here" and \`..\` to refer to "the parent directory."

*Pro Tip:* Use the \`~\` (tilde) character as a shortcut for your home directory. \`cd ~\`, \`cd\`, and \`cd /home/$USER\` all lead to the same place.`
            },
            {
                title: 'The Filesystem Hierarchy Standard (FHS)',
                content: `Linux directories aren't random; they follow the Filesystem Hierarchy Standard (FHS). This standard ensures that software and administrators know exactly where to find specific types of data across different Linux distributions.

**Critical Directories Showcase:**
*   \`/etc\`: The system's brain. Contains all system-wide configuration files.
*   \`/bin\` & \`/usr/bin\`: The system's toolbox. Contains the executable programs.
*   \`/var\`: The system's memory. Contains variable data like logs, caches, and databases.
*   \`/home\`: The users' space. Every user gets a private folder here.
*   \`/root\`: The superuser's private home directory.

*Real-World Example:* If your website isn't loading, the first place you check is \`/var/log/httpd/\` or \`/var/log/nginx/\` to find the error logs. If you need to change the system's hostname, you edit the file \`/etc/hostname\`. Knowing these locations by heart is what separates a novice from a master.`
            },
            {
                title: 'Manipulating Files and Directories',
                content: `Creating, moving, and deleting files is the bread and butter of system administration. However, in Linux, these operations are often performed with powerful flags that allow for bulk operations and safety checks.

**The Essential Command Suite:**
*   \`mkdir -p\`: Creates parent directories as needed. \`mkdir -p project/src/utils\` creates three levels of folders at once.
*   \`cp -a\`: The "archive" copy. It preserves permissions, timestamps, and symbolic links, which is crucial for backups.
*   \`mv\`: Used for both moving and renaming. In Linux, renaming is just moving a file to a new name in the same spot.
*   \`rm -i\`: The "interactive" remove. It asks for confirmation before deleting, saving you from accidental data loss.

*Safety Warning:* The command \`rm -rf /\` is a legendary "system-killer." It recursively and forcefully deletes everything starting from the root. Never run this unless you explicitly intend to destroy the entire OS.`
            }
        ]
    },
    'sys1-ch03': {
        chapterId: 'sys1-ch03',
        sections: [
            {
                title: 'The "man" Pages',
                content: 'The most important skill in Linux is knowing how to find help. The `man` command (manual) is the standard documentation system. Typing `man <command>` opens a detailed reference page covering syntax, flags, and examples.'
            },
            {
                title: 'Navigating Documentation',
                content: 'Use the arrow keys to scroll, `/` to search for text, and `q` to quit. For even more detailed info, use the `info` command, which provides hyperlinked documentation.'
            },
            {
                title: '/usr/share/doc',
                content: 'Many packages install additional documentation, READMEs, and example configuration files into `/usr/share/doc`. This is a goldmine for troubleshooting specific applications.'
            }
        ]
    },
    'sys1-ch04': {
        chapterId: 'sys1-ch04',
        sections: [
            {
                title: 'Input and Output Redirection',
                content: 'By default, commands print to the screen (stdout). You can redirect this output to a file using `>`. For example, `ls > list.txt` creates a file with the directory listing. Use `>>` to append to a file instead of overwriting it.'
            },
            {
                title: 'The Power of Pipes',
                content: 'Pipes (`|`) allow you to use the output of one command as the input for another. This "chaining" lets you build complex workflows. For example, `ls -l /etc | grep ".conf"` lists only the configuration files in the etc directory.'
            },
            {
                title: 'Basic Text Editing with vim',
                content: '`vim` is the standard terminal editor. It has two main modes:\n\n1. **Command Mode:** (Default) For navigation and deleting text.\n2. **Insert Mode:** (Press `i`) For typing text.\n\nTo save and quit, press `Esc`, type `:wq`, and hit `Enter`.'
            }
        ]
    },
    'sys1-ch05': {
        chapterId: 'sys1-ch05',
        sections: [
            {
                title: 'Understanding Users and Groups',
                content: 'Linux is a multi-user system. Every process and file belongs to a user and a group. Users are defined in `/etc/passwd`, and groups in `/etc/group`. The root user (UID 0) is the superuser with total control over the system.'
            },
            {
                title: 'Managing Accounts',
                content: 'Use `useradd` to create a user and `usermod` to modify existing accounts. To set a password, use `passwd <username>`. Groups are managed with `groupadd` and `groupmod`.'
            },
            {
                title: 'Switching Identities',
                content: 'Use `su - <username>` to switch to another user. More commonly, use `sudo` to run commands with administrative privileges without needing the root password.'
            }
        ]
    },
    'sys1-ch06': {
        chapterId: 'sys1-ch06',
        sections: [
            {
                title: 'Standard Linux Permissions (UGO)',
                content: 'Permissions are split into three categories: User (owner), Group, and Others. Each category can have Read (r=4), Write (w=2), and Execute (x=1) permissions. Use `ls -l` to view these as a string like `rwxr-xr-x`.'
            },
            {
                title: 'Changing Permissions & Ownership',
                content: 'Use `chmod` to change permissions (e.g., `chmod 644 file.txt`) and `chown` to change the owner or group (e.g., `chown user:group file.txt`).'
            },
            {
                title: 'Special Permissions',
                content: 'Beyond rwx, there are special bits:\n\n* **SUID:** Executable runs as the file owner.\n* **SGID:** Executable runs as the file group, or new files in a directory inherit the directory group.\n* **Sticky Bit:** Only the file owner can delete their files in a shared directory (e.g., `/tmp`).'
            }
        ]
    },
    'sys1-ch07': {
        chapterId: 'sys1-ch07',
        sections: [
            {
                title: 'What is a Process?',
                content: 'A process is an instance of a running program. Every process has a unique Process ID (PID). The first process started by the kernel is `systemd` (PID 1), which manages all other processes.'
            },
            {
                title: 'Monitoring Tools',
                content: 'Use `ps aux` for a snapshot of all running processes. For a real-time, interactive view, use `top` or `htop`. These tools show CPU usage, memory consumption, and process states.'
            },
            {
                title: 'Controlling Processes',
                content: 'You can manage processes using signals with the `kill` command. Common signals include:\n\n* `SIGTERM` (15): Request graceful termination.\n* `SIGKILL` (9): Force immediate termination.\n* `SIGSTOP` (19): Pause a process.'
            }
        ]
    },
    'sys1-ch08': {
        chapterId: 'sys1-ch08',
        sections: [
            {
                title: 'The systemd Init System',
                content: 'Modern Enterprise Linux uses `systemd` to manage services and daemons. It uses "unit files" to define how services should start and what their dependencies are.'
            },
            {
                title: 'Using systemctl',
                content: 'The `systemctl` command is your primary tool for service management:\n\n* `systemctl start <name>`: Start a service.\n* `systemctl stop <name>`: Stop a service.\n* `systemctl status <name>`: Check if a service is running and view recent logs.'
            },
            {
                title: 'Enabling Services at Boot',
                content: 'Starting a service doesn\'t mean it will start automatically after a reboot. Use `systemctl enable <name>` to configure a service to start at boot, and `systemctl disable` to prevent it.'
            }
        ]
    },
    'sys1-ch09': {
        chapterId: 'sys1-ch09',
        sections: [
            {
                title: 'Secure Shell (SSH)',
                content: 'SSH is the standard protocol for secure remote management. It encrypts all traffic between the client and the server, preventing password sniffing and man-in-the-middle attacks.'
            },
            {
                title: 'Key-Based Authentication',
                content: 'Instead of passwords, use SSH keys for better security and automation. Generate a pair with `ssh-keygen`, and transfer the public key to the server using `ssh-copy-id`.'
            },
            {
                title: 'Securing the SSH Daemon',
                content: 'Configure `/etc/ssh/sshd_config` to improve security. Best practices include disabling root login (`PermitRootLogin no`) and disabling password authentication (`PasswordAuthentication no`) once keys are set up.'
            }
        ]
    },
    'sys1-ch10': {
        chapterId: 'sys1-ch10',
        sections: [
            {
                title: 'System Logging',
                content: 'Linux logs almost everything. Historical logs are stored in `/var/log`. Key files include `/var/log/messages` (global system logs) and `/var/log/secure` (authentication logs).'
            },
            {
                title: 'The systemd Journal',
                content: '`systemd-journald` collects logs from the kernel and services in a high-performance binary format. Use `journalctl` to query these logs. It allows filtering by time, service, or priority.'
            },
            {
                title: 'Log Rotation',
                content: 'To prevent logs from filling up the disk, the `logrotate` utility automatically compresses and archives old log files based on age or size.'
            }
        ]
    },
    'sys1-ch11': {
        chapterId: 'sys1-ch11',
        sections: [
            {
                title: 'Networking Basics',
                content: 'Enterprise Linux uses NetworkManager to manage connectivity. Network interfaces are typically named `eth0` or `enp0s3`. Use `ip addr` to view your current IP addresses.'
            },
            {
                title: 'Configuring with nmcli',
                content: 'The `nmcli` command is the powerful CLI for NetworkManager. You can use it to create connections, set static IPs, configure DNS, and bring interfaces up or down.'
            },
            {
                title: 'Testing Connectivity',
                content: 'Use `ping` to test basic connectivity to another host. Use `ip route` to view the routing table and verify your default gateway. `tracepath` can help identify where a network connection is failing.'
            }
        ]
    },
    'sys1-ch12': {
        chapterId: 'sys1-ch12',
        sections: [
            {
                title: 'Archiving with tar',
                content: 'The `tar` (tape archive) utility groups multiple files into a single "tarball". It doesn\'t compress by default, but it can use utilities like `gzip` or `bzip2` to create smaller files (e.g., `.tar.gz`).'
            },
            {
                title: 'Remote Copy (scp)',
                content: '`scp` allows you to securely copy files between hosts over SSH. The syntax is similar to `cp`, but you include the remote host and path (e.g., `scp file.txt user@remote:/tmp`).'
            },
            {
                title: 'Syncing with rsync',
                content: '`rsync` is a more advanced tool that only copies the *differences* between files. It is ideal for backups and large data transfers because it can resume interrupted copies and preserve file permissions.'
            }
        ]
    },
    'sys1-ch13': {
        chapterId: 'sys1-ch13',
        sections: [
            {
                title: 'RPM and DNF',
                content: 'Enterprise Linux uses the RPM package format. `dnf` (Dandified YUM) is the modern package manager that handles dependency resolution, repository management, and updates.'
            },
            {
                title: 'Managing Software',
                content: 'Common `dnf` commands:\n\n* `dnf install <package>`: Install software.\n* `dnf remove <package>`: Uninstall software.\n* `dnf update`: Update all installed packages to the latest versions.'
            },
            {
                title: 'Repositories and Modules',
                content: 'Software is organized into repositories. Enterprise Linux also uses "Application Streams" (AppStream), allowing you to choose between different versions (modules) of software like Python or MariaDB.'
            }
        ]
    },
    'sys1-ch14': {
        chapterId: 'sys1-ch14',
        sections: [
            {
                title: 'Block Devices and Partitions',
                content: 'Physical disks are represented as block devices in `/dev` (e.g., `/dev/sda`). Before use, they are typically split into partitions using tools like `fdisk` or `parted`.'
            },
            {
                title: 'File Systems and Mounting',
                content: 'A partition must be formatted with a file system (typically XFS or EXT4) before it can store files. To access the file system, it must be "mounted" to a directory in the hierarchy.'
            },
            {
                title: 'Persistent Mounts (/etc/fstab)',
                content: 'Manual mounts disappear after a reboot. The `/etc/fstab` file defines which file systems should be mounted automatically at boot time. Incorrect entries here can prevent the system from booting!'
            }
        ]
    },
    'sys1-ch15': {
        chapterId: 'sys1-ch15',
        sections: [
            {
                title: 'Analyzing System Health',
                content: 'As a sysadmin, you must ensure the server is healthy. Use `df -h` to check disk space and `free -m` to check memory usage. High "load averages" in `uptime` indicate a bottlenecked CPU or I/O.'
            },
            {
                title: 'The sosreport Utility',
                content: 'When a system has a complex issue, use `sosreport`. It collects a massive amount of configuration and diagnostic information into a single archive that can be sent to support teams.'
            },
            {
                title: 'Getting Support',
                content: 'Documentation is your first line of defense. Use `man`, official system documentation, and the customer portal. If the issue persists, professional support contracts provide access to expert engineers.'
            }
        ]
    }
    // Content for further chapters (CH06-CH27) will follow the same detailed pattern.
};
