export interface ChapterSection {
    title: string;
    content: string;
}

export interface ChapterContent {
    chapterId: string;
    sections: ChapterSection[];
}

export const chapterContents: Record<string, ChapterContent> = {
    'sys1-ch01': {
        chapterId: 'sys1-ch01',
        sections: [
            {
                title: 'Introduction to Linux Mastery',
                content: `Linux is not just an operating system; it is the backbone of the modern internet, cloud computing, and high-performance clusters. Mastering Linux means gaining direct control over your system, understanding the principles of open-source collaboration, and developing the skills required to manage everything from a personal server to a massive corporate infrastructure.

In this track, we move beyond the superficial "click-and-point" interfaces of consumer operating systems and dive into the "Terminal-First" philosophy. This approach prioritizes efficiency, automation, and deep system understanding. By the end of this curriculum, you will not just be a "user" of Linux, but a skilled practitioner capable of architecting and maintaining complex systems.

**Key Mastery Principles:**
*   **The Command Line is Truth:** GUI tools are abstractions. The CLI provides the raw, unadulterated power of the system.
*   **Everything is a File:** From hardware devices to system configurations, Linux treats almost everything as a file, making the filesystem the ultimate configuration interface.
*   **Small Tools, Big Results:** The Unix philosophy of building small, focused tools that do one thing well and piping them together is the secret to Linux productivity.

*Example Showcase:* Instead of searching through menus to find a specific setting, a single command like \`grep -r "SearchTerm" /etc/\` can find configuration entries across thousands of files in milliseconds.`
            },
            {
                title: 'The Graphical Interface vs. The TTY',
                content: `While modern Linux distributions often come with beautiful desktop environments like GNOME, KDE, or XFCE, a professional administrator must be equally comfortable in a headless environment. The Graphical User Interface (GUI) is excellent for multitasking and media, but the TeleTYpe (TTY) or terminal is where the heavy lifting happens.

GNOME (GNU Network Object Model Environment) is the default for many professional-grade distributions. It provides a distraction-free workflow with the "Activities Overview" serving as a central hub for window management. However, as your skills grow, you'll find yourself spending more time in terminal emulators like GNOME Terminal, Alacritty, or Kitty.

**Understanding the Stack:**
1.  **The Kernel:** The heart of the system that manages hardware and memory.
2.  **The Shell:** The command interpreter (like Bash or Zsh) that translates your keystrokes into system calls.
3.  **The Terminal Emulator:** The windowed application that gives you a visual interface to the shell.

*Use Case:* Imagine you need to update 50 servers. Doing this through a GUI would take hours. Using a shell and a small script, you can trigger the update on all 50 machines simultaneously with a single command.`
            },
            {
                title: 'The Architecture of the Shell',
                content: `When you open a terminal, you are greeted by a "prompt." This prompt is generated by your shell, most commonly Bash (Bourne Again SHell). The shell is your primary interface for interacting with the Linux kernel. It supports variables, loops, conditional logic, and most importantly, command execution.

The shell follows a specific execution cycle:
1.  **Read:** It waits for you to type a command and hit Enter.
2.  **Evaluate:** It parses the command, expands variables, and finds the executable in your system's PATH.
3.  **Execute:** It tells the kernel to start a new process for that command.
4.  **Loop:** It returns the prompt and waits for the next instruction.

*Example:* When you type \`ls -l\`, the shell finds the \`ls\` binary in \`/usr/bin\`, tells the kernel to run it with the \`-l\` argument, captures the output, and prints it to your screen. Understanding this lifecycle is critical for troubleshooting "command not found" errors or permission issues.`
            }
        ]
    },
    'sys1-ch02': {
        chapterId: 'sys1-ch02',
        sections: [
            {
                title: 'Navigating the Unified Filesystem',
                content: `Unlike Windows, which uses drive letters like C: and D:, Linux uses a single unified tree structure. Everything starts at the **Root** directory, represented by a single forward slash (\`/\`). Every file, directory, and even hardware device is a branch on this tree.

Navigating this tree efficiently is a foundational skill. The \`cd\` (change directory) command is your primary tool for movement, and \`pwd\` (print working directory) tells you exactly where you are in the vast forest of the filesystem.

**The Power of Paths:**
*   **Absolute Paths:** Always start from the root (\`/\`). They are unambiguous and work from anywhere. Example: \`/var/log/syslog\`.
*   **Relative Paths:** Start from your current location. They are shorter but depend on context. Example: \`../backups/old_logs\`.
*   **The Dot Notation:** Use \`.\` to refer to "here" and \`..\` to refer to "the parent directory."

*Pro Tip:* Use the \`~\` (tilde) character as a shortcut for your home directory. \`cd ~\`, \`cd\`, and \`cd /home/$USER\` all lead to the same place.`
            },
            {
                title: 'The Filesystem Hierarchy Standard (FHS)',
                content: `Linux directories aren't random; they follow the Filesystem Hierarchy Standard (FHS). This standard ensures that software and administrators know exactly where to find specific types of data across different Linux distributions.

**Critical Directories Showcase:**
*   \`/etc\`: The system's brain. Contains all system-wide configuration files.
*   \`/bin\` & \`/usr/bin\`: The system's toolbox. Contains the executable programs.
*   \`/var\`: The system's memory. Contains variable data like logs, caches, and databases.
*   \`/home\`: The users' space. Every user gets a private folder here.
*   \`/root\`: The superuser's private home directory.

*Real-World Example:* If your website isn't loading, the first place you check is \`/var/log/httpd/\` or \`/var/log/nginx/\` to find the error logs. If you need to change the system's hostname, you edit the file \`/etc/hostname\`. Knowing these locations by heart is what separates a novice from a master.`
            },
            {
                title: 'Manipulating Files and Directories',
                content: `Creating, moving, and deleting files is the bread and butter of system administration. However, in Linux, these operations are often performed with powerful flags that allow for bulk operations and safety checks.

**The Essential Command Suite:**
*   \`mkdir -p\`: Creates parent directories as needed. \`mkdir -p project/src/utils\` creates three levels of folders at once.
*   \`cp -a\`: The "archive" copy. It preserves permissions, timestamps, and symbolic links, which is crucial for backups.
*   \`mv\`: Used for both moving and renaming. In Linux, renaming is just moving a file to a new name in the same spot.
*   \`rm -i\`: The "interactive" remove. It asks for confirmation before deleting, saving you from accidental data loss.

*Safety Warning:* The command \`rm -rf /\` is a legendary "system-killer." It recursively and forcefully deletes everything starting from the root. Never run this unless you explicitly intend to destroy the entire OS.`
            }
        ]
    },
    'sys1-ch03': {
        chapterId: 'sys1-ch03',
        sections: [
            {
                title: 'Mastering the Help System',
                content: `In the world of Linux, you are never truly lost if you know how to find help. The system is designed with a "self-documenting" philosophy. Almost every command and configuration file has a corresponding manual page, often referred to as a **man page**. These pages are the definitive source of truth, providing syntax, flag descriptions, and occasionally, valuable examples.

The \`man\` command is your gateway to this knowledge. For example, typing \`man ls\` will open the manual for the list command. The content is organized into sections (e.g., Section 1 for user commands, Section 5 for file formats, Section 8 for administrative commands). Mastering the navigation of these pages is a prerequisite for system mastery.

**Navigation Shortcuts:**
*   **Spacebar:** Scroll down one page.
*   **u / d:** Scroll up or down half a page.
*   **g / G:** Jump to the very top or bottom of the page.
*   **q:** Quit the viewer and return to the shell.

*Pro Tip:* Use \`man -k <keyword>\` to search for commands related to a specific topic. If you forgot how to change passwords, \`man -k password\` will show you a list of relevant man pages.`
            },
            {
                title: 'Searching and Filtering Within Manuals',
                content: `Reading a man page from start to finish is rarely necessary. Instead, you should learn to search for specific flags or keywords while the manual is open. By pressing the \`/\` (forward slash) key, you enter "Search Mode." Type your keyword and hit Enter; the viewer will highlight all occurrences.

You can navigate through the results using the \`n\` key (next result) and \`N\` key (previous result). This is incredibly useful for finding a specific flag in a massive manual like \`find\` or \`grep\`.

**The Alternative: pinfo and info**
While \`man\` is the standard, some packages use the \`info\` format, which supports hyperlinked documentation. The \`pinfo\` tool is a more modern, colorful alternative to the standard \`info\` viewer, allowing you to click through links using the arrow keys and Enter.

*Use Case:* You need to find the specific flag for \`tar\` that preserves permissions but forgot what it's called. Instead of scrolling, you run \`man tar\`, type \`/permission\`, and hit \`n\` until you find the \`-p\` flag description.`
            },
            {
                title: 'The Goldmine: /usr/share/doc',
                content: `Manual pages are excellent for command references, but what about complex software suites or example configurations? For this, we turn to the \`/usr/share/doc\` directory. Every package installed on your system typically creates a folder here containing READMEs, change logs, and most importantly, sample configuration files.

Exploring this directory is often the fastest way to learn how to configure a new service like Apache, Nginx, or a database. Instead of searching the internet for a configuration template, you can often find a perfectly commented example right on your own disk.

**Exploration Workflow:**
1.  Navigate to the directory: \`cd /usr/share/doc\`.
2.  Find your package: \`ls | grep nginx\`.
3.  Look for examples: \`ls nginx*/examples\`.

*Example Showcase:* If you are setting up a firewall for the first time, checking the documentation in \`/usr/share/doc/firewalld/\` can provide you with ready-to-use XML templates that follow best practices.`
            }
        ]
    },
    'sys1-ch04': {
        chapterId: 'sys1-ch04',
        sections: [
            {
                title: 'The Three Standard Streams',
                content: `Every command you run in a Linux shell is connected to three data "streams." Understanding how to manipulate these streams is what allows you to chain commands together and automate complex tasks.

1.  **Standard Input (stdin / 0):** Data flowing *into* the command (usually from your keyboard).
2.  **Standard Output (stdout / 1):** The normal output flowing *out* of the command (usually to your screen).
3.  **Standard Error (stderr / 2):** Error messages flowing *out* of the command.

By default, both stdout and stderr appear on your screen, which can be confusing. Redirection allows you to separate them or save them to files for later analysis.

*Example:* Run \`ls /nonexistent 2> errors.log\`. The error message won't show on your screen; it will be saved into the \`errors.log\` file.`
            },
            {
                title: 'Redirection: Capturing and Appending',
                content: `Redirection operators are the steering wheel of the shell. They allow you to tell a command exactly where its output should go or where its input should come from.

**Primary Operators:**
*   \`>\`: Overwrite redirection. \`ls > file.txt\` creates a new file (or wipes the old one) and puts the output inside.
*   \`>>\`: Append redirection. \`ls >> file.txt\` adds the output to the end of an existing file.
*   \`<\`: Input redirection. \`sort < names.txt\` feeds the content of the file into the sort command as if you typed it.

**Advanced Redirection:**
You can redirect both stdout and stderr simultaneously using \`&>\`. This is common in automation scripts where you want a complete log of everything a command did, including its failures.

*Showcase:* \`./backup_script.sh &> backup.log\` will capture every single line of output from your script into a log file, ensuring no errors are missed.`
            },
            {
                title: 'The Power of the Pipe (|)',
                content: `The pipe character (\`|\`) is perhaps the most iconic feature of the Unix/Linux philosophy. It allows you to take the **stdout** of one command and immediately use it as the **stdin** of another. This allows you to build "one-liner" programs that perform massive amounts of data processing without ever creating a temporary file.

Chaining pipes together creates a "pipeline." Each command in the pipe acts as a filter, transforming the data as it passes through.

**The Master Pipeline Example:**
\`cat /var/log/secure | grep "Failed password" | awk '{print $11}' | sort | uniq -c | sort -nr\`

*What does this do?*
1.  Reads the security logs (\`cat\`).
2.  Filters for failed login attempts (\`grep\`).
3.  Extracts the IP addresses (\`awk\`).
4.  Sorts them for grouping (\`sort\`).
5.  Counts the unique occurrences of each IP (\`uniq -c\`).
6.  Sorts them by frequency (\`sort -nr\`).

This single line provides a real-time list of the most frequent attackers attempting to brute-force your system. This is the power of Linux Mastery.`
            },
            {
                title: 'Professional Text Editing with Vim',
                content: `As a system administrator, you will spend a significant portion of your life editing configuration files. While there are many editors available, \`vim\` (Vi IMproved) is the industry standard because it is installed on almost every Linux system by default and is designed for pure efficiency.

Vim is a **modal editor**, meaning the keys behave differently depending on which "mode" you are in. This is confusing for beginners but allows masters to edit text without ever touching a mouse.

**The Three Essential Modes:**
1.  **Normal Mode:** (Default) For moving around and deleting text. Press \`Esc\` to return here.
2.  **Insert Mode:** For typing text. Press \`i\` to enter.
3.  **Command Mode:** For saving and quitting. Type \`:\` followed by a command (e.g., \`:wq\` to save and quit).

*Mastery Tip:* Use \`u\` to undo, \`Ctrl+r\` to redo, and \`dd\` to delete an entire line. Once you learn these shortcuts, you will never want to go back to a standard "notepad" style editor.`
            }
        ]
    },
    'sys1-ch05': {
        chapterId: 'sys1-ch05',
        sections: [
            {
                title: 'Understanding Multi-User Linux Architecture',
                content: `Linux was built from the ground up as a multi-user operating system. This means multiple people can be logged in and running processes simultaneously without interfering with each other. This is made possible through a strict separation of identities and resources. Every action on the system is performed on behalf of a **User**, and users are often grouped into **Groups** for easier permission management.

The "Root" user (UID 0) is the all-powerful superuser. Root can read any file, stop any process, and change any setting. For security reasons, a master administrator rarely logs in as root directly. Instead, they use a standard user account and elevate their privileges only when necessary.

**Key Identity Databases:**
*   \`/etc/passwd\`: Contains user account information (username, UID, home directory, shell). Contrary to its name, it does *not* contain passwords.
*   \`/etc/shadow\`: Securely stores encrypted passwords and account expiration details. Only root can read this file.
*   \`/etc/group\`: Defines the groups on the system and lists their members.

*Mastery Concept:* UIDs (User IDs) are what the kernel actually cares about. The username is just a human-friendly label. If two accounts have UID 1000, the kernel treats them as the exact same person.`
            },
            {
                title: 'Managing Local Accounts and Passwords',
                content: `Creating and maintaining user accounts is a core administrative task. While many systems use centralized directories like LDAP or Active Directory, knowing how to manage local accounts is critical for system recovery and standalone servers.

**The Administrative Command Suite:**
*   \`useradd -m\`: Creates a new user and automatically sets up their home directory from a template in \`/etc/skel\`.
*   \`usermod -aG\`: Appends a user to a supplementary group. This is the standard way to grant a user permission to use things like Docker or high-performance networking.
*   \`userdel -r\`: Deletes a user and removes their home directory and mail spool.
*   \`passwd -e\`: Forces a user to change their password the next time they log in. This is a common security practice for new hires.

*Use Case:* When a new developer joins the team, you would run \`useradd -m devname\`, then \`usermod -aG developers devname\` to give them access to shared projects, and finally \`passwd devname\` to set their initial temporary credentials.`
            },
            {
                title: 'Elevating Privileges: sudo vs. su',
                content: `In the early days of Linux, administrators would use \`su\` (Substitute User) to become root. This required sharing the root password, which is a significant security risk. Modern systems prefer \`sudo\` (SuperUser DO).

\`sudo\` allows a user to run a command with the privileges of another user (usually root) while using their *own* password for authentication. This provides a clear audit trail in \`/var/log/secure\`, as the system logs exactly who ran which command.

**The Configuration Gateway: /etc/sudoers**
The \`/etc/sudoers\` file controls who can use sudo. You should never edit this file directly with a standard editor; always use \`visudo\`. This command checks your syntax before saving, preventing you from accidentally locking yourself out of administrative access.

*Showcase:* To give a user full administrative power, you typically add them to the \`wheel\` or \`sudo\` group. The line \`%wheel ALL=(ALL) ALL\` in sudoers tells the system that any member of the wheel group can run any command on any host as any user.`
            }
        ]
    },
    'sys1-ch06': {
        chapterId: 'sys1-ch06',
        sections: [
            {
                title: 'The Linux Permission Model (UGO)',
                content: `Security in Linux is primarily enforced through file permissions. Every file and directory is owned by a **User** and a **Group**. Access is then defined for three categories: the **User** (owner), the **Group**, and **Others** (everyone else). This is the "UGO" model.

**The Three Basic Permissions:**
1.  **Read (r):** Ability to view file content or list directory contents.
2.  **Write (w):** Ability to modify file content or create/delete files within a directory.
3.  **Execute (x):** Ability to run a file as a program or "enter" (cd into) a directory.

*Critical Distinction:* To delete a file, you don't need write permission on the file itself; you need write permission on the **directory** that contains it. This is a common point of confusion for new administrators.`
            },
            {
                title: 'Mastering Octal and Symbolic Notation',
                content: `Permissions are often represented as a string like \`-rwxr-xr-x\`. The first character represents the type (\`-\` for file, \`d\` for directory). The next nine characters are the UGO permissions.

Administrators use the \`chmod\` (change mode) command to modify these. You can use **Symbolic** notation (\`u+x\` to add execute to owner) or **Octal** notation (\`755\`).

**The Octal Math:**
*   Read = 4
*   Write = 2
*   Execute = 1
*   Summing them gives the permission level (e.g., 4+2+1 = 7 for rwx).

*Example Showcase:* A common secure permission for a sensitive script is \`700\` (\`rwx------\`), meaning only the owner can do anything with it. A public web folder is often set to \`755\` (\`rwxr-xr-x\`), allowing anyone to view the site but only the owner to update the files.`
            },
            {
                title: 'Special Bits: SUID, SGID, and Sticky',
                content: `Beyond standard rwx, Linux has three "Special Bits" that handle advanced security scenarios.

1.  **SUID (Set User ID):** When set on an executable, the program runs with the privileges of the file's *owner*, not the user who started it. This is how the \`passwd\` command can modify \`/etc/shadow\`.
2.  **SGID (Set Group ID):** On a directory, this ensures that any new files created inside inherit the group of the parent directory, rather than the user's primary group. This is essential for shared team folders.
3.  **Sticky Bit:** Primarily used on shared directories like \`/tmp\`. It ensures that users can only delete files that they personally own, preventing them from wiping out other people's temporary data.

*Pro Tip:* You can spot these in \`ls -l\` output by looking for an 's' or 't' instead of 'x' in the permission string (e.g., \`rwsr-xr-x\` for SUID).`
            },
            {
                title: 'Default Permissions and umask',
                content: `When you create a new file, how does Linux decide its initial permissions? This is controlled by the **umask** (user file-creation mask). The umask is a value that is "subtracted" from the system's maximum possible permissions (usually 666 for files and 777 for directories).

A typical system umask is \`0022\`.
*   Start with: 777 (Directory)
*   Minus umask: 022
*   Result: 755 (\`rwxr-xr-x\`)

*Use Case:* If you are working in a highly secure environment and want every new file you create to be private by default, you would set your umask to \`0077\`. This ensures that new files are created with \`600\` permissions and directories with \`700\`.`
            }
        ]
    },
    'sys1-ch07': {
        chapterId: 'sys1-ch07',
        sections: [
            {
                title: 'What is a Process?',
                content: `In Linux, a process is an instance of a running program. When you execute a command, the system creates a new process to carry out the instructions. Each process is isolated from others, having its own memory space and resources. Every process in the system is assigned a unique **Process ID (PID)**.

Processes exist in a parent-child hierarchy. The kernel starts the first process, \`systemd\` (PID 1), which then spawns all other system and user processes. This tree-like structure allows the system to track dependencies and manage the lifecycle of applications effectively.

**Process States:**
*   **Running (R):** The process is currently using the CPU or is in the queue to use it.
*   **Sleeping (S/D):** The process is waiting for an event (like a keystroke or disk I/O). 'S' is interruptible, 'D' is uninterruptible (waiting for hardware).
*   **Stopped (T):** The process has been paused (e.g., by \`Ctrl+Z\`).
*   **Zombie (Z):** The process has finished execution but is waiting for its parent to acknowledge its exit.

*Showcase:* Use the \`pstree\` command to see a visual representation of this hierarchy. You will see how your terminal shell is a child of the terminal emulator, which is a child of the desktop manager.`
            },
            {
                title: 'Monitoring System Load and Processes',
                content: `Real-time monitoring is critical for maintaining system performance. A master administrator must be able to identify resource-hungry processes before they cause a system crash.

**The Monitoring Toolkit:**
*   \`ps aux\`: A "snapshot" of every process running on the system. 'a' for all users, 'u' for user-friendly format, 'x' for processes not attached to a terminal.
*   \`top\`: The classic interactive monitor. It provides a live view of CPU usage, memory, and the "Load Average."
*   \`htop\`: A more modern, colorful, and user-friendly version of top. It allows you to scroll and kill processes using intuitive keybinds.

**Understanding Load Average:**
You'll see three numbers like \`0.05, 0.15, 0.50\`. These represent the average system load over the last 1, 5, and 15 minutes. If these numbers are higher than the number of CPU cores in your system, your machine is "overloaded" and processes are waiting in a queue.

*Use Case:* If the system feels sluggish, you run \`top\`, press \`M\` to sort by memory usage, and identify that a runaway web browser process is consuming 90% of your RAM.`
            },
            {
                title: 'Controlling Processes with Signals',
                content: `Linux processes are controlled using **Signals**. A signal is a simple message sent to a process to request a specific action. The \`kill\` command is the standard tool for sending these signals, though its name is a bit misleading—it can do much more than just "killing."

**Commonly Used Signals:**
*   \`SIGTERM (15)\`: The polite request. It tells the process to save its data and exit gracefully. This is the default signal.
*   \`SIGKILL (9)\`: The hammer. It forces the kernel to terminate the process immediately. The process cannot ignore this signal.
*   \`SIGSTOP (19)\`: Pauses the process without ending it.
*   \`SIGCONT (18)\`: Resumes a stopped process.

*Mastery Tip:* Use \`killall <name>\` to send a signal to every process with a specific name, or \`pkill -u <user>\` to stop all processes belonging to a specific person. This is essential for clearing out "stuck" sessions.`
            }
        ]
    },
    'sys1-ch08': {
        chapterId: 'sys1-ch08',
        sections: [
            {
                title: 'The systemd Init System',
                content: `Modern Linux distributions have moved away from legacy "SysVinit" scripts in favor of **systemd**. Systemd is the first process to start (PID 1) and is responsible for bringing the system to a usable state by starting services, managing hardware, and monitoring the system's health.

Systemd uses "Units" to define resources. The most common is the **Service Unit** (\`.service\`), but there are also **Socket Units** for networking and **Target Units** (like \`multi-user.target\`) which define the system's "state" or "runlevel."

**Why systemd?**
*   **Parallelism:** It starts services simultaneously to speed up boot times.
*   **On-Demand Activation:** Services can be started only when they are actually needed.
*   **Robust Logging:** It integrates deeply with the system journal for centralized logging.

*Showcase:* Run \`systemctl list-units --type=service\` to see every service currently managed by systemd and its status.`
            },
            {
                title: 'Managing Services with systemctl',
                content: `The \`systemctl\` command is the primary interface for managing the lifecycle of services. Whether you are starting a web server or troubleshooting a failing database, this is the tool you will use.

**The Essential Workflow:**
*   \`systemctl start <name>\`: Immediately starts the service.
*   \`systemctl stop <name>\`: Stops the running service.
*   \`systemctl restart <name>\`: Stops and then starts the service (used after configuration changes).
*   \`systemctl status <name>\`: The most important command. It tells you if the service is active, shows the PID, and provides the last few lines of the service's log.

*Pro Tip:* If a service is "masked," it cannot be started manually or automatically. This is a way to permanently disable a service. Use \`systemctl unmask <name>\` to restore it.`
            },
            {
                title: 'Persistence: Enable vs. Start',
                content: `A common mistake for new administrators is forgetting that \`start\` is temporary. If you start a service and the system reboots, the service will not come back unless it is **Enabled**.

*   **Enable:** Creates a symbolic link in the systemd configuration so the service starts automatically at boot.
*   **Disable:** Removes the link so the service stays off after a reboot.

**Verifying Persistence:**
Use \`systemctl is-enabled <name>\` to check the boot-time status.

*Use Case:* You have installed a new firewall. You run \`systemctl start firewalld\` to protect the system immediately, and then \`systemctl enable firewalld\` to ensure the protection persists through the next power cycle.`
            }
        ]
    },
    'sys1-ch09': {
        chapterId: 'sys1-ch09',
        sections: [
            {
                title: 'Secure Shell (SSH) Fundamentals',
                content: `SSH is the standard protocol for secure remote login and other secure network services over an insecure network. In the past, administrators used insecure protocols like Telnet, which sent passwords in plain text. SSH encrypts all traffic (including passwords), effectively eliminating eavesdropping, connection hijacking, and other attacks.

The SSH architecture consists of a client (the machine you are on) and a server (the remote machine running \`sshd\`). When you connect, the two machines perform a cryptographic handshake to establish a secure tunnel.

**Common Connection Syntax:**
\`ssh username@remote-host\`

*Mastery Concept:* By default, SSH runs on port 22. Changing this port is a simple but effective way to reduce the noise in your logs from automated bots trying to brute-force common passwords.`
            },
            {
                title: 'Key-Based Authentication: Beyond Passwords',
                content: `Passwords are a weak link in system security. Key-based authentication is much more secure and convenient. It uses a pair of cryptographic keys: a **Private Key** (which stays on your local machine) and a **Public Key** (which is placed on the server).

**The Setup Workflow:**
1.  **Generate:** \`ssh-keygen -t ed25519\` creates a modern, highly secure key pair.
2.  **Transfer:** \`ssh-copy-id username@remote-host\` automatically places your public key in the server's \`~/.ssh/authorized_keys\` file.
3.  **Login:** Now, when you connect, the server challenges your client to prove it has the private key. No password required.

*Pro Tip:* Always protect your private key with a passphrase. If your local machine is ever compromised, the attacker still cannot use your keys without the passphrase.`
            },
            {
                title: 'Hardening the SSH Daemon',
                content: `As an administrator, you must secure the SSH entry point. The configuration file is located at \`/etc/ssh/sshd_config\`. 

**Security Best Practices:**
*   \`PermitRootLogin no\`: Forces administrators to log in as a standard user and then use \`sudo\`.
*   \`PasswordAuthentication no\`: Disables password logins entirely, allowing *only* key-based entry. This makes brute-force attacks impossible.
*   \`AllowUsers\`: Specify a list of exactly which users are allowed to connect remotely.

*Showcase:* After making changes to the config, always run \`sshd -t\` to test the syntax before restarting the service with \`systemctl restart sshd\`. A single typo in this file can lock you out of your server permanently.`
            }
        ]
    },
    'sys1-ch10': {
        chapterId: 'sys1-ch10',
        sections: [
            {
                title: 'The scp and sftp Commands',
                content: `Transferring files securely between systems is a daily task for any Linux professional. The \`scp\` (Secure Copy) and \`sftp\` (Secure File Transfer Protocol) tools use the same secure tunnel provided by SSH.

*   **scp:** Best for quick, one-off file copies. The syntax is similar to the local \`cp\` command: \`scp file.txt user@remote:/path/to/destination\`.
*   **sftp:** Provides an interactive interface similar to FTP but fully encrypted. It is better for browsing remote directories and transferring multiple files in a single session.

*Example:* To download a directory from a remote server, use the recursive flag: \`scp -r user@remote:/var/www/html ./local_backup\`.`
            },
            {
                title: 'Rsync: The King of File Synchronization',
                content: `While \`scp\` is simple, \`rsync\` is the professional's choice for backups and large data transfers. Unlike \`scp\`, which copies everything every time, \`rsync\` uses a "delta-transfer algorithm" to only copy the *differences* between files.

**Key Advantages:**
*   **Efficiency:** If a 1GB file has 1MB of changes, rsync only sends that 1MB.
*   **Interrupted Transfers:** Rsync can resume partially completed transfers.
*   **Attribute Preservation:** It can preserve permissions, timestamps, symbolic links, and ownership with the \`-a\` (archive) flag.

*Mastery Command:* \`rsync -avz --progress /source/dir/ user@remote:/destination/dir/\`. The \`-z\` flag compresses data during transfer, making it much faster over slow connections.`
            },
            {
                title: 'Professional Backups with Tar and Rsync',
                content: `Combining \`tar\` (Tape Archive) with \`rsync\` creates a powerful backup strategy. \`tar\` is used to package many files and directories into a single compressed archive (often called a "tarball"), while \`rsync\` ensures that archive is safely stored on a remote backup server.

**The Archive Workflow:**
1.  \`tar -czf backup.tar.gz /home/user/data\`: Creates a compressed (\`-z\`) archive.
2.  \`rsync -a backup.tar.gz backup-server:/backups/\`: Synchronizes it to the remote storage.

*Use Case:* An automated "cron job" runs this script every night at 2 AM, ensuring that even if the main server's disk fails, the data is safe and easily restorable from the compressed tarball on the remote server.`
            }
        ]
    },
    'sys1-ch11': {
        chapterId: 'sys1-ch11',
        sections: [
            {
                title: 'Introduction to Software Repositories',
                content: `Unlike other operating systems where you download installers from various websites, Linux uses a centralized system of **Repositories**. A repository is a secure, curated server containing thousands of software packages that have been tested and verified to work together on your specific distribution.

The package manager handles the heavy lifting of downloading, installing, and—most importantly—resolving dependencies. If a program needs a specific library to run, the package manager will automatically find and install that library for you.

**The Main Components:**
*   **Packages:** Usually \`.rpm\` files containing the software, metadata, and scripts.
*   **Metadata:** Information about what's inside the repo (versions, dependencies).
*   **DNF (Dandified YUM):** The modern command-line tool used to interact with these repositories.

*Mastery Concept:* Repositories ensure that your entire system stays consistent. When you update your system, you aren't just updating the OS; you are updating every single app installed from a repository simultaneously.`
            },
            {
                title: 'Mastering the dnf Command',
                content: `The \`dnf\` command is the successor to the classic \`yum\`. it is faster, has better dependency resolution, and uses less memory. Mastering its subcommands is essential for any Linux administrator.

**Common Operations:**
*   \`dnf install <package>\`: Downloads and installs software.
*   \`dnf remove <package>\`: Uninstalls software and can optionally clean up unneeded dependencies.
*   \`dnf search <keyword>\`: Looks through the metadata to find packages related to your needs.
*   \`dnf info <package>\`: Provides a detailed description, version number, and license information before you install.

*Showcase:* Use \`dnf history\` to see a list of every transaction ever performed. If a recent installation broke your system, you can use \`dnf history undo <id>\` to roll back the changes exactly as they were.`
            },
            {
                title: 'System Updates and Security Patches',
                content: `Keeping a system up to date is the first line of defense against security threats. Linux makes this incredibly easy with a single command.

*   \`dnf check-update\`: Lists which packages have newer versions available.
*   \`dnf upgrade\`: Downloads and installs all available updates for the system.

**Partial Updates:**
Sometimes you only want to update security-related packages without touching the rest of the system. You can do this with \`dnf upgrade --security\`. This is common in production environments where you want to minimize the risk of a version jump breaking your custom applications.

*Use Case:* On a production web server, you might set up a "cron job" to run \`dnf upgrade -y --security\` every night at midnight. This ensures that even if a new zero-day vulnerability is discovered, your system is patched automatically within hours.`
            }
        ]
    },
    'sys1-ch12': {
        chapterId: 'sys1-ch12',
        sections: [
            {
                title: 'Storage Devices and Partitions',
                content: `In Linux, everything is a file, including your hard drive. Your primary disk is usually represented as a file like \`/dev/sda\` or \`/dev/nvme0n1\`. Before you can store data on a disk, it must be **Partitioned**.

A partition is a logical division of a physical disk. This allows you to separate the Operating System from user data, or even run multiple operating systems on the same drive.

**Partition Tables:**
*   **MBR (Legacy):** Limited to 4 primary partitions and 2TB disks.
*   **GPT (Modern):** Supports virtually unlimited partitions and massive disks (up to 9.4 Zettabytes).

*Mastery Tool:* \`fdisk -l\` provides a list of all disks and their current partition layouts. For a more interactive and modern experience, use \`gdisk\` for GPT disks.`
            },
            {
                title: 'The Filesystem Hierarchy and Mount Points',
                content: `Once a partition is created, it must be formatted with a **Filesystem** (like XFS or ext4) and then **Mounted** into the directory tree. In Linux, there are no "C:" or "D:" drives. Instead, every disk partition is attached to a specific folder, known as a **Mount Point**.

**The Mounting Workflow:**
1.  **Format:** \`mkfs.xfs /dev/sdb1\` creates the filesystem structures.
2.  **Mount Point:** \`mkdir /data\` creates the destination folder.
3.  **Mount:** \`mount /dev/sdb1 /data\` attaches the storage.

*Use Case:* You have added a new high-speed SSD to your server for a database. You partition it, format it with XFS for performance, and mount it at \`/var/lib/mysql\`. Now, all database data is stored on the fast SSD, while the OS stays on the slower primary drive.`
            },
            {
                title: 'Swap Space: Virtual Memory',
                content: `Swap is a dedicated area on your disk that the Linux kernel uses as "Virtual Memory." When your physical RAM is full, the kernel moves inactive data to the swap space to prevent the system from crashing.

While swap is much slower than RAM, it is essential for system stability. You can create swap as a dedicated partition or as a simple **Swap File**.

**Managing Swap:**
*   \`mkswap\`: Formats a partition or file for use as swap.
*   \`swapon\`: Activates the swap space.
*   \`free -m\`: Shows exactly how much RAM and Swap is currently in use.

*Pro Tip:* The "swappiness" value (0-100) controls how aggressively the kernel uses swap. A value of 10 means "only use swap if absolutely necessary," while 60 is the balanced default.`
            }
        ]
    },
    'sys1-ch13': {
        chapterId: 'sys1-ch13',
        sections: [
            {
                title: 'The Flexibility of Logical Volume Management (LVM)',
                content: `Traditional partitioning is rigid. If you run out of space on a partition, resizing it often requires taking the system offline and moving data around. **Logical Volume Management (LVM)** solves this by adding a layer of abstraction between the physical disks and the filesystem.

With LVM, you don't create partitions; you create a **Volume Group** (a pool of storage) and then carve out **Logical Volumes** from that pool. These logical volumes can be resized on-the-fly, even while the system is running.

**The Three Layers of LVM:**
1.  **Physical Volumes (PV):** The raw disks or partitions (e.g., \`/dev/sdb\`).
2.  **Volume Groups (VG):** The "pool" that combines multiple PVs into one giant block of storage.
3.  **Logical Volumes (LV):** The "virtual partitions" that you actually format and use.

*Mastery Concept:* LVM allows you to span a single filesystem across multiple physical disks. If your storage pool is running low, you can simply plug in a new drive, add it to the Volume Group, and expand your Logical Volume instantly.`
            },
            {
                title: 'Managing LVM: Create, Extend, and Snapshot',
                content: `LVM provides a powerful set of commands to manage your storage pool. Once you understand the PV -> VG -> LV flow, the commands become very intuitive.

**The Creation Workflow:**
*   \`pvcreate /dev/sdb\`: Prepare the disk.
*   \`vgcreate data_pool /dev/sdb\`: Create the pool.
*   \`lvcreate -L 10G -n my_data data_pool\`: Create a 10GB volume.

**The Expansion Workflow:**
One of the best features of LVM is the ability to grow a volume. If you need more space:
1.  \`lvextend -L +5G /dev/data_pool/my_data\`: Grow the logical volume.
2.  \`xfs_growfs /data\`: Grow the filesystem to fill the new space.

*Showcase:* LVM also supports **Snapshots**. A snapshot is a point-in-time copy of a volume. You can take a snapshot before a risky upgrade, and if things go wrong, you can revert the entire volume to its previous state in seconds.`
            },
            {
                title: 'LVM Best Practices and Use Cases',
                content: `LVM is the default storage configuration for most professional Linux distributions for a reason. It provides the reliability and flexibility required for enterprise environments.

**Key Use Cases:**
*   **Database Servers:** Databases often grow unpredictably. LVM allows you to add storage without downtime.
*   **Thin Provisioning:** You can create a 100GB volume even if you only have 50GB of physical disk. The system only uses physical space as data is actually written. This is called "over-provisioning."
*   **Data Migration:** You can move a running Logical Volume from an old, slow disk to a new, fast SSD without unmounting the filesystem.

*Pro Tip:* Use \`vgs\` and \`lvs\` for quick summaries of your storage pool, or \`vgdisplay\` and \`lvdisplay\` for deep technical details including UUIDs and physical extent sizes.`
            }
        ]
    },
    'sys1-ch14': {
        chapterId: 'sys1-ch14',
        sections: [
            {
                title: 'The Virtual File System (VFS)',
                content: `Linux treats everything as a file, and the **Virtual File System (VFS)** is the kernel layer that makes this possible. VFS acts as a translator between the kernel and the various types of filesystems (XFS, ext4, NFS, etc.). This allows the system to interact with a local hard drive, a network share, and a virtual memory file using the exact same commands (\`ls\`, \`cp\`, \`mv\`).

The VFS manages the **Directory Tree**. Unlike other systems where each drive has its own root (A:, C:, etc.), Linux has a single, unified root directory (\`/\`). Every storage device is "attached" to this tree.

**Key VFS Concepts:**
*   **Inodes:** The "ID card" for a file, containing metadata (owner, size, timestamps) but not the filename or the actual data.
*   **Dentries:** Directory entries that link filenames to Inodes.
*   **Superblocks:** Contain information about the filesystem as a whole (total size, block size).

*Mastery Concept:* When you move a file within the same partition, the data never actually moves. Only the "Dentry" (the link between the name and the Inode) is updated. This is why moving a 10GB file on the same disk is instantaneous.`
            },
            {
                title: 'The /etc/fstab: Automating Mounts',
                content: `Mounting a drive manually with the \`mount\` command is fine for temporary tasks, but for a system to be usable, it must mount its drives automatically at boot. This is controlled by the \`/etc/fstab\` (File System Table) file.

A typical fstab entry has six fields:
1.  **Device:** Usually identified by its **UUID** (Universally Unique ID) to ensure it stays consistent even if disk names change.
2.  **Mount Point:** Where the drive should appear (e.g., \`/home\`).
3.  **Filesystem Type:** (e.g., \`xfs\`).
4.  **Options:** (e.g., \`defaults,noatime,rw\`).
5.  **Dump:** Legacy backup flag (usually 0).
6.  **Pass:** Order for checking the disk at boot (1 for root, 2 for others).

*Showcase:* Use the \`blkid\` command to find the UUID of your partitions. Copying this UUID into your fstab is much safer than using \`/dev/sda1\`, which might change to \`/dev/sdb1\` if you plug in a USB drive.`
            },
            {
                title: 'Mounting Network Storage (NFS)',
                content: `In a professional environment, data is often stored on a centralized server and shared across the network. The **Network File System (NFS)** allows a remote directory to be mounted as if it were a local disk.

**The NFS Workflow:**
1.  **Client Tool:** Install \`nfs-utils\`.
2.  **Discovery:** \`showmount -e <server-ip>\` to see available shares.
3.  **Mount:** \`mount -t nfs <server-ip>:/shared/data /mnt/remote\`.

*Use Case:* An entire office of Linux workstations can mount a shared \`/home\` directory from a central NFS server. This allows users to sit down at any machine and have access to all of their personal files and settings instantly.`
            }
        ]
    },
    'sys1-ch15': {
        chapterId: 'sys1-ch15',
        sections: [
            {
                title: 'Analyzing System Health and Performance',
                content: `A master administrator is the "doctor" for their servers. You must be able to diagnose bottlenecks and health issues before they lead to downtime. This involves monitoring three critical resources: **CPU**, **Memory**, and **Disk I/O**.

**The Vital Signs Monitor:**
*   \`uptime\`: Shows how long the system has been running and the Load Average.
*   \`free -h\`: Displays available and used memory in a human-readable format.
*   \`df -h\`: Lists the usage of all mounted filesystems.
*   \`iostat\`: (From the sysstat package) Shows how hard your disks are working.

*Mastery Tip:* If \`df -h\` shows a partition at 100%, services will fail. If \`free -h\` shows low "available" memory and high "swap used," your system is likely slow because it's constantly swapping data to the disk.`
            },
            {
                title: 'Troubleshooting with the sosreport Utility',
                content: `When a system has a critical failure that you cannot diagnose locally, you turn to \`sosreport\`. This tool collects a massive amount of configuration data, system logs, and hardware info into a single compressed archive.

This archive is designed to be sent to professional support teams or senior architects. It provides a complete "snapshot" of the system's state, allowing for deep analysis without needing direct access to the live machine.

**Usage:** Simply run \`sosreport\` as root. The process takes a few minutes and outputs a \`.tar.xz\` file in \`/var/tmp\`.

*Use Case:* A kernel panic occurs intermittently. You run \`sosreport\` to capture the current state of kernel modules, network configs, and system logs to send to a specialized engineer for post-mortem analysis.`
            },
            {
                title: 'The Support Ecosystem: Documentation and Portals',
                content: `Linux Mastery is not about knowing everything; it's about knowing where to find the answer. The professional ecosystem is built on robust documentation and support portals.

**Information Sources:**
1.  **Local Docs:** \`man\`, \`info\`, and \`/usr/share/doc\`.
2.  **Official Documentation:** Detailed guides for every major component of the system.
3.  **Knowledge Bases:** Curated articles on common issues and professional best practices.

*Final Mastery Advice:* Always keep a "lab environment" where you can test risky commands or configuration changes before applying them to a live production server. This is the hallmark of a true professional.`
            }
        ]
    }
};
